config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  root 'jobs#index'
  resources :jobs do
   member do
     post :accept
     post :reject
     post :apply_job
     post :hire
     post :fire

   end
 end
 

  devise_for :users, controllers: { registrations: 'registrations' }
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
	#mount_uploader :attachment
	mount_uploader :attachment

end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!
  def index

  	#if (current_user.has_role? :admin)

		@jobs = Job.all 
	#end	
  end

  def new
  	@job = Job.new
  end 

  def create
#debugger
  	@job = Job.new
  	@job.job_type = job_params[:job_type]
  	@job.user_id = current_user.id
  	@job.job_stutes = "add"
  	@job.save



  end


  def accept
  	#debugger
  	@job = Job.find(params[:id])
  	@job.update(job_stutes: "accept")
  	@job.save




  end
  def reject
  	@job = Job.find(params[:id])
  	@job.update(job_stutes: "reject")
  	@job.save


  end


  def apply_job
  	@job = Job.find(params[:id])
  	@job.update(job_stutes: "applying")
  	@job.save


  end
  def hire
  	#debugger
  	@job = Job.find(params[:id])
  	@job.update(job_stutes: "hire")
  	@job.save




  end
  def fire
  	#debugger
  	@job = Job.find(params[:id])
  	@job.update(job_stutes: "fire")
  	@job.save




  end
  def job_params
        params.require(:job).permit(:job_type , :job_stutes)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]

  # POST /resource
  def create
    super
    resource.add_role(params[:user][:roles])
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [roles: []])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/index.html.erb
<h1>Jobs#index</h1>
<p>Find me in app/views/jobs/index.html.erb</p>
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>


<h1>jobs.all</h1>

<ul>
  <% @jobs.each do |job| %>
    <li>
     <h4>job_id</h4><%= job.id %>
     <h4>job_type</h4> <%= job.job_type %>
      <%#= job.user_id%>
     


    </li>
  <% end %>
</ul>

<% if (current_user.has_role? :employer) %>

	

			<h1>your_job</h1>

			<ul>
			  <% @jobs.each do |job| %>
		<% if (job.user_id  == current_user.id) %>
				<h4>job_id</h4><%= job.id %>
				<h4>job_type</h4> <%= job.job_type %>  
				<% if (job.job_stutes == "applying") %>
					    <li>
					     <h4>job_id</h4><%= job.id %>
					     <h4>job_type</h4> <%= job.job_type %>
					      <%#= job.user_id%>
					     <h4>job_stutes</h4><%= job.job_stutes%>
					     <td><%= button_to 'hire',  hire_job_path(job.id), method: :hire   %></td>
					     <td><%= button_to 'fire',  fire_job_path(job.id), method: :fire   %></td>


					    </li>
					  	<% end %>
						</ul>
				<% end %>	
		<%end%>		

		<%= link_to "New job", new_job_path %>

<%end%>

<% if (current_user.has_role? :admin) %>
	<h1>admin review </h1>
<%#debugger%>
	
		<ul>
	  <% @jobs.each do |job| %>
	  <% if (job.job_stutes == "add") %>
			    <li>
			     <h4>job_id</h4><%= job.id %>
			     <h4>job_type</h4> <%= job.job_type %>
			      <%#= job.user_id%>
			     <h4>job_stutes</h4><%= job.job_stutes%>

			     <td><%= button_to 'accept',  accept_job_path(job.id), method: :accept   %></td>
			     <td><%= button_to 'reject',  reject_job_path(job.id), method: :reject   %></td>


			    </li>
		<%end%>	    
	  <% end %>
	</ul>

		

<%end%>		
<% if (current_user.has_role? :user) %>
	<h1>current opning</h1>
<%#debugger%>
	
		<ul>
	  <% @jobs.each do |job| %>
	  <% if (job.job_stutes == "accept") %>
			    <li>
			     <h4>job_id</h4><%= job.id %>
			     <h4>job_type</h4> <%= job.job_type %>
			      <%#= job.user_id%>
			     <h4>job_stutes</h4><%= job.job_stutes%>

			     <td><%= button_to 'apply_job',  apply_job_job_path(job.id), method: :apply_job   %></td>

			        <%#= form_for @job , url: apply_job_job_path(job.id), method: :apply_job do |f| %>
			         
			           <%#= f.label :attachment %>
			           <%#= f.file_field :attachment %>
			           <%#= f.submit "apply_job" %>
			        <% #end %>
			     </div>
			    


			    </li>
		<%end%>	    
	  <% end %>
	</ul>

		

<%end%>	

app/views/jobs/new.html.erb
<%= form_with model: @job do |form| %>
  <div>
    <%= form.label :job_type %><br>
    <%= form.text_field :job_type %>
   
  </div>



  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demojob</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
           <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>